[package]
name = "node_comm_listener"
version = "0.1.0"
authors = ["Daniel Orf <dorf@suse.com>"]
edition = "2018"

[dependencies]
zmq = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_cbor = "0.9.0"
tokio = "0.1.21" 

[features]
vendored-zmq = ['zmq/vendored']
