[package]
name = "nickel"
version = "0.1.0"
authors = ["Daniel Orf <dorf@suse.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.nickel]
version = "*"